Fixed: Railway env token for railway up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,8 +48,7 @@ jobs:
             npm install -g @railway/cli
 
             echo "Deploying to Railway..."
-            echo "$RAILWAY_TOKEN" | railway login --browserless
-            railway up --service 43ab57fd-00b3-4426-b182-f3781038b227 -d || echo "Railway deploy failed"
+            railway up --service 43ab57fd-00b3-4426-b182-f3781038b227 -d -- --token=$RAILWAY_TOKEN || echo "Railway deploy failed"
             echo "Railway deploy finished"
 
             echo "Stopping pidstat..."
